### ISSUE TITLE
1.15.2 Rendering/loading error?

### ISSUE THREAD

**Issue by raspberrybug** [MysticMods/Druidcraft#51]
### General Information

**Describe the bug:**
I played Minecraft with some mods, then I tried to load it with Druidcraft and it just crashes immediately or it'll load for like 5 minutes and then stay frozen. I don't know if this is a problem with my laptop, but the crash report specifically said there was an error with Druidcraft and there was also a problem with rendering overlays and it also said there's not enough data available to load.

**To Reproduce:**
1. Download Druidcraft 1.15-0.4.21 or 1.15-0.4.2 (I tried both) and put in the mods folder
2. Download other mods (included in the crash report)
3. Run Minecraft with Forge version 1.15.2-31.2.27

**Expected behavior:**
Minecraft will either crash and bring up a crash report or the loading screen will freeze after it loads all the mod libraries and screens them

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.15.2-2.0.0

**Other Versions:**
- Other mods you think could cause issues: all in 1.15.2
- Forge: 1.15.2-forge-31.2.27
- Minecraft: 1.15.2

***

### Logging Information

**Crash]Report (if available):**
[pastebin](https://pastebin.com/ZtHdMdrJ)

**Latest Log (if necessary):**
[28Jun2020 19:00:45.453] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, berristrawberri, --version, 1.15.2-forge-31.2.27, --gameDir, C:\Users\NAME\AppData\Roaming\.minecraft, --assetsDir, C:\Users\NAME\AppData\Roaming\.minecraft\assets, --assetIndex, 1.15, --uuid, b4202c17beeb4a5296ca254e8ace5261, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.27, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[28Jun2020 19:00:45.465] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[28Jun2020 19:00:52.788] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[28Jun2020 19:00:59.195] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.15.2-forge-31.2.27, --gameDir, C:\Users\NAME\AppData\Roaming\.minecraft, --assetsDir, C:\Users\NAME\AppData\Roaming\.minecraft\assets, --uuid, b4202c17beeb4a5296ca254e8ace5261, --username, berristrawberri, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release]
[28Jun2020 19:01:05.758] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: berristrawberri
[28Jun2020 19:01:54.189] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[28Jun2020 19:02:04.286] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity clumps:xp_orb_big
[28Jun2020 19:02:04.718] [modloading-worker-0/INFO] [JarSignVerifier/]: Mod usefulbackpacks is signed with a valid certificate.
[28Jun2020 19:02:05.112] [modloading-worker-0/INFO] [JarSignVerifier/]: Mod uteamcore is signed with a valid certificate.
[28Jun2020 19:02:05.444] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 31.2.27, for MC 1.15.2 with MCP 20200515.085601
[28Jun2020 19:02:05.445] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.2.27 Initialized
[28Jun2020 19:02:09.747] [modloading-worker-2/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity cfm:seat
[28Jun2020 19:02:11.048] [Render thread/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Dispatching synchronous work after CONSTRUCT: 2 jobs
[28Jun2020 19:02:11.170] [Render thread/INFO] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.080
[28Jun2020 19:02:11.424] [Render thread/INFO] [mcwbridges/]: Blocks registered.
[28Jun2020 19:02:11.767] [Render thread/INFO] [mcwbridges/]: Items registered.
[28Jun2020 19:02:12.161] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity abnormals_core:boat
[28Jun2020 19:02:12.162] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity autumnity:snail
[28Jun2020 19:02:13.564] [Render thread/WARN] [net.minecraft.resources.ResourcePackInfo/]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\NAME\AppData\Roaming\.minecraft\resourcepacks\Phoebe's Pack.mcpack.zip'
[28Jun2020 19:02:13.633] [Render thread/WARN] [net.minecraft.resources.ResourcePackInfo/]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\NAME\AppData\Roaming\.minecraft\resourcepacks\Phoebe's Pack.mcpack.zip'
[28Jun2020 19:02:19.699] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[28Jun2020 19:02:20.398] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Mod Resources, Default, Mizunos 16 Craft JE_1.15.2-1.1.zip
[28Jun2020 19:02:22.023] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1621) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.2.jar:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53) ~[?:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler$$Lambda$3123/1281605986.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$3122/1471743583.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_51]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$null$5(ModLoader.java:153) ~[?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$3121/116076392.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:109) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:153) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3116/2020348502.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2080/1788048182.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3113/353922272.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2080/1788048182.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51]
	... 5 more
[28Jun2020 19:02:26.586] [Render thread/WARN] [net.minecraft.resources.ResourcePackInfo/]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\NAME\AppData\Roaming\.minecraft\resourcepacks\Phoebe's Pack.mcpack.zip'
[28Jun2020 19:02:26.587] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[28Jun2020 19:06:39.650] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
[28Jun2020 19:06:39.976] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Shutdown failure!
java.lang.NullPointerException: null
	at net.minecraft.client.renderer.model.ModelManager.close(ModelManager.java:102) ~[?:?]
	at net.minecraft.client.Minecraft.close(Minecraft.java:852) [?:?]
	at net.minecraft.client.Minecraft.func_71405_e(Minecraft.java:839) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:218) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.27.jar:31.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$416/1964926542.call(Unknown Source) [forge-1.15.2-31.2.27.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]

**Comment by VulpTheHorseDog** [comment]
Not sure exactly what's happening here. The log doesn't point to my mod at all, does removing my mod actually fix the problem?

**Comment by noobanidus** [comment]
> [28Jun2020 19:02:26.586] [Render thread/WARN] [net.minecraft.resources.ResourcePackInfo/]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\NAME\AppData\Roaming.minecraft\resourcepacks\Phoebe's Pack.mcpack.zip'

Your resource pack is faulty.

**Comment by noobanidus** [comment]
And I'm also going to guess that one of your config files is corrupted. Try deleting the Druidcraft one?
