### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by TechniumUnlimited** [MysticMods/Druidcraft#87]
Druidcraft-1.16.4-0.4.5.jar
Forge: 35.1.37

Crash Report: https://pastebin.com/5PDdWQJQ

```Details:
	Mod File: Druidcraft-1.16.4-0.4.5.jar
	Failure message: Druidcraft (druidcraft) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: 1024
	Mod Version: 0.4.5
	Mod Issue URL: https://github.com/MysticMods/Druidcraft/issues
	Exception message: java.lang.ArrayIndexOutOfBoundsException: 1024
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1124) ~[?:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.insert(Object2FloatOpenHashMap.java:272) ~[?:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.put(Object2FloatOpenHashMap.java:280) ~[?:?] {re:classloading}
	at com.vulp.druidcraft.registry.VanillaIntegrationRegistry.setup(VanillaIntegrationRegistry.java:31) ~[druidcraft:1.16.4-0.4.5] {re:classloading}
	at com.vulp.druidcraft.Druidcraft.setup(Druidcraft.java:48) ~[druidcraft:1.16.4-0.4.5] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_261] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_261] {}```

**Comment by TechniumUnlimited** [comment]
hmm... may have had nothing to do with druidcraft in the end - I think I was not supposed to change the worldtype in forge-common.toml and removed batteries mod (also mentioned in crash log - and world loaded on server fine now.

**Comment by GreyMario** [comment]
@TechniumUnlimited This is because you have exceeded the maximum ID range for blocks. You need to install Just Enough IDs to bypass this limitation of Minecraft 1.12.

**Comment by TechniumUnlimited** [comment]
Im actually using 1.16.4 version, not sure if that matters

**Comment by Vaelzan** [comment]
I've mentioned the cause to the devs on Discord and I think they're going to get it fixed soon, but it's caused by registering the vanilla integration (think compostable, flammable) in a way that isn't thread safe. It will only rarely crash.

**Comment by GreyMario** [comment]
...why is there a 1024 limit in 1.16

**Comment by Vaelzan** [comment]
> ...why is there a 1024 limit _of any kind_ in 1.16

There isn't. Those objects are resizable, and it's trying to access something outside of the *current* (not maximum) upper bounds.

I mentioned the actual cause in my own comment above.
